# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 309d43527c8ddc7b6e76f552d1eec005b85c032e90aab173ddca5d60953be0e31fa9dfb8308a9ccf94bd1038c35cccb818d76cc2498ae9d976d8a9abe9f629cb

test:
  secret_key_base: 34e0014fd00bc32e8b633697d51000f0a61badcf004796016185977ffdc64d3bfc77be8ee40838b5ed5bfd44fcb9f3ef9905d980c6aa3810396eb0d9f0241fe1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
